# Generated by Django 3.2.13 on 2022-08-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0004_user_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_profit',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=256)),
                ('total_profit', models.FloatField(default=0)),
                ('is_repeat', models.BooleanField(default=False)),
                ('bot_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_camp_set', to='analytic.campaign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user_set', to='analytic.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
