# Generated by Django 3.2.13 on 2022-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20220621_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_withdrawal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
    ]
