# Generated by Django 3.2.13 on 2022-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20220624_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hot_balance_trx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hot_balance_usdt',
            field=models.FloatField(default=0),
        ),
    ]
