# Generated by Django 3.2.13 on 2022-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220701_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='key1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='key2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='key3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
