# Generated by Django 3.2.13 on 2022-07-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20220701_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_ref_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_ref_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_ref_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='funds_raised_ref_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='funds_raised_ref_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='funds_raised_ref_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_1_id_user_set', to='tgbot.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_2_id_user_set', to='tgbot.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_3_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_3_id_user_set', to='tgbot.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_ref_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_ref_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reward_ref_3',
            field=models.IntegerField(default=0),
        ),
    ]
