# Generated by Django 3.2.13 on 2022-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_auto_20220704_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='funds_raised_ref_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='funds_raised_ref_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='funds_raised_ref_3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='reward_ref_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='reward_ref_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='reward_ref_3',
            field=models.FloatField(default=0),
        ),
    ]
