# Generated by Django 3.2.13 on 2022-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_user_max_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timestamp', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_set', to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
